import type { WorldState } from "./world";

/** Locked Forklight demo warehouse. baselineMetrics filled at bootstrap. */
export const LOCKED_WORLD: WorldState = {
  revision: 1,
  seed: 42,
  name: "Forklight Demo Warehouse",
  baselineMetrics: null,
  entities: [
    {
      id: "spawn-1",
      type: "spawn",
      name: "Inbound Dock",
      position: { x: 2, y: 0, z: 8 },
      size: { w: 2, h: 1, d: 2 },
      protected: true,
      capacity: 99,
    },
    {
      id: "dest-1",
      type: "destination",
      name: "Outbound Dock",
      position: { x: 22, y: 0, z: 8 },
      size: { w: 2, h: 1, d: 2 },
      protected: true,
      capacity: 99,
    },
    {
      id: "pack-1",
      type: "machine",
      name: "Packing Station",
      position: { x: 14, y: 0, z: 8 },
      size: { w: 2, h: 1.5, d: 2 },
      protected: true,
      capacity: 1,
    },
    {
      id: "scan-1",
      type: "machine",
      name: "Scanner",
      position: { x: 14, y: 0, z: 12 },
      size: { w: 2, h: 1.5, d: 2 },
      protected: true,
      capacity: 2,
    },
    {
      id: "j-center",
      type: "junction",
      name: "Center Hub",
      position: { x: 8, y: 0, z: 8 },
      size: { w: 1.5, h: 0.5, d: 1.5 },
      protected: true,
      capacity: 2,
    },
    {
      id: "j-north",
      type: "junction",
      name: "North Hub",
      position: { x: 8, y: 0, z: 12 },
      size: { w: 1.5, h: 0.5, d: 1.5 },
      protected: false,
      capacity: 3,
    },
    {
      id: "j-south",
      type: "junction",
      name: "South Hub",
      position: { x: 8, y: 0, z: 3 },
      size: { w: 1.5, h: 0.5, d: 1.5 },
      protected: false,
      capacity: 3,
    },
    {
      id: "barrier-north",
      type: "barrier",
      name: "North Barrier",
      position: { x: 7, y: 0, z: 11.3 },
      size: { w: 1.5, h: 1.5, d: 1.0 },
      protected: false,
      capacity: 0,
    },
    {
      id: "barrier-south",
      type: "barrier",
      name: "South Barrier",
      position: { x: 7, y: 0, z: 3.8 },
      size: { w: 1.5, h: 1.5, d: 1.0 },
      protected: false,
      capacity: 0,
    },
    {
      id: "rack-1",
      type: "barrier",
      name: "Overflow Rack",
      position: { x: 11, y: 0, z: 14 },
      size: { w: 1.2, h: 1.2, d: 1.2 },
      protected: false,
      capacity: 0,
    },
  ],
  routes: [
    {
      id: "r-main",
      name: "Main Corridor",
      sourceId: "spawn-1",
      targetId: "dest-1",
      speed: 0.5,
      capacity: 3,
      enabled: true,
      waypoints: [
        { x: 2, z: 8 },
        { x: 8, z: 8 },
        { x: 14, z: 8 },
        { x: 22, z: 8 },
      ],
    },
    {
      id: "r-north",
      name: "North Bypass",
      sourceId: "spawn-1",
      targetId: "dest-1",
      speed: 0.5,
      capacity: 3,
      enabled: false,
      waypoints: [
        { x: 2, z: 8 },
        { x: 8, z: 12 },
        { x: 14, z: 12 },
        { x: 22, z: 8 },
      ],
    },
    {
      id: "r-south",
      name: "South Bypass",
      sourceId: "spawn-1",
      targetId: "dest-1",
      speed: 0.5,
      capacity: 3,
      enabled: false,
      waypoints: [
        { x: 2, z: 8 },
        { x: 8, z: 3 },
        { x: 18, z: 3 },
        { x: 22, z: 8 },
      ],
    },
  ],
};

export const LOCKED_MUTATIONS = {
  openNorth: { entityId: "barrier-north", position: { x: 11, z: 11.3 } },
  openSouth: { entityId: "barrier-south", position: { x: 11, z: 3.8 } },
  moveProtectedScanner: {
    entityId: "scan-1",
    position: { x: 14, z: 12.5 },
  },
  followScannerWaypoint: { x: 14, z: 12.5 },
} as const;
